// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXcEyUzkb9Fp0poYZa6q-89Hv-3HQVzZI',
    appId: '1:530612344632:web:6f448970cabbfeee9693cd',
    messagingSenderId: '530612344632',
    projectId: 'flutter-firebase-1fa91',
    authDomain: 'flutter-firebase-1fa91.firebaseapp.com',
    storageBucket: 'flutter-firebase-1fa91.appspot.com',
    measurementId: 'G-71X8BETX4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdRwjxxEPaLDydqgRgRRbr8Bpln8vmtNc',
    appId: '1:530612344632:android:a997a274dfb8b9689693cd',
    messagingSenderId: '530612344632',
    projectId: 'flutter-firebase-1fa91',
    storageBucket: 'flutter-firebase-1fa91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCra3abDHPaT6GKZ2yq9Wj6-NkBQniY8Mo',
    appId: '1:530612344632:ios:815ce9f0c31e1c419693cd',
    messagingSenderId: '530612344632',
    projectId: 'flutter-firebase-1fa91',
    storageBucket: 'flutter-firebase-1fa91.appspot.com',
    iosBundleId: 'com.example.authWithFirebase',
  );
}
